CREATE TABLE VISIT_T(
	   id VARCHAR2(30 CHAR) REFERENCES USER_T(USERID)
	 , context VARCHAR2(1000 CHAR) NOT NULL
     , createdate DATE DEFAULT(SYSDATE)
);

INSERT INTO VISIT_T VALUES('아이디','내용 작성',DEFAULT);



SELECT *FROM VISIT_T;


SELECT * 
  FROM(
    SELECT ROWNUM AS N 
	     , ID
	     , CONTEXT
	 	 , CREATEDATE
	  FROM (SELECT *FROM VISIT_T ORDER BY CREATEDATE DESC)
	  )
WHERE N BETWEEN 11 AND 15;


SELECT COUNT(*) FROM VISIT_T ;

/** 
SELECT ROWNUM
     , EMPLOYEE_ID
     , FIRST_NAME
     , LAST_NAME
     , SALARY
  FROM (SELECT EMPLOYEE_ID
  			 , FIRST_NAME
  			 , LAST_NAME
  			 , SALARY
          FROM EMPLOYEES
         ORDER BY SALARY DESC)
 WHERE ROWNUM<=10;
 */
	


DROP TABLE VISIT_T;

SELECT * FROM BOOKMARK_T;
DROP TABLE BOOKMARK_T;


CREATE TABLE BOOKMARK_T(
	   ID NUMBER PRIMARY KEY
	 , USERID VARCHAR2(20) REFERENCES USER_T(USERID)
	 , URL VARCHAR2(100)
	 , NAME VARCHAR2(100)
);

INSERT INTO BOOKMARK_T VALUES(1,'아이디' ,'https://naver.com','네이버');
INSERT INTO BOOKMARK_T VALUES(2,'아이디','https://google.com','구글');

INSERT INTO BOOKMARK_T VALUES(3,'1234' ,'https://nate.com','네이트');
INSERT INTO BOOKMARK_T VALUES(4,'1234','https://daum.net','구글');
CREATE TABLE USER_T(
	   USERID   VARCHAR2(20) PRIMARY KEY
	 , PASSWORD VARCHAR2(20) NOT NULL
	 , EMAIL    VARCHAR2(100)
);

SELECT ID, USERID, URL, NAME FROM BOOKMARK_T WHERE USERID ='아이디'


SELECT * FROM BOOKMARK_T;

SELECT * FROM USER_T;




