/*
 * 부서별 평균 급여를 집계한 DEPT_AVG_SALARY 테이블을 만들어
 * 데이터를 추가하시오
 */
CREATE TABLE DEPT_AVG_SALARY
AS
SELECT FLOOR(AVG(SALARY)) AS SALARY 
	 , DEPARTMENT_ID  AS DEPT_ID
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID;

DROP TABLE DEPT_AVG_SALARY;
SELECT * FROM DEPT_AVG_SALARY;
/*
 * 직급별 평균, 최대, 최소 급여를 집계한 JOB_SALARY_STATUS 테이블을 만들어 
 * 데이터를 추가하시오
 */
CREATE TABLE JOB_SALARY_STATUS
AS
SELECT FLOOR(AVG(SALARY)) AS 평균
     , MAX(SALARY) AS 최대
     , MIN(SALARY) AS 최소
     , JOB_ID
  FROM EMPLOYEES
 GROUP BY JOB_ID ;
SELECT * FROM JOB_SALARY_STATUS;
DROP TABLE JOB_SALARY_STATUS;
/*
 * 직급 ID에 'MGR'이 접두사로 붙은 JOB_SALARY_STATUS에 평균, 최대, 최소 급여를 +500 하세요
 */
UPDATE JOB_SALARY_STATUS SET 평균= 평균+500 , 최대= 최대+500 , 최소= 최소+500 
WHERE JOB_ID LIKE  '%MGR'; 

/*
 * 년도별 입사 인원을 파악하기 위한 HIRE_FOR_YEAR 테이블을 만들어 데이터를 추가 하시오
 * (인원 파악이 주 목적이기 때문에 년도와 인원수만 저장할 수 있으면 됨)
 */
CREATE TABLE HIRE_FOR_YEAR
AS
SELECT EXTRACT(YEAR FROM HIRE_DATE) AS 입사년도
     , COUNT(*) AS 입사자수
  FROM EMPLOYEES
 GROUP BY EXTRACT(YEAR FROM HIRE_DATE)
 ORDER BY 1;

SELECT * FROM HIRE_FOR_YEAR;
DROP TABLE HIRE_FOR_YEAR;
/*
 * 부서별/직급별 평균, 최대, 최소 급여를 저장한 테이블에 COMMISSION_PCT까지 반영한
 * 데이터가 저장될 수 있도록 기존 정보를 수정하시오
 */
CREATE TABLE JOB_DEPT_SALARY_STATUS
AS
SELECT FLOOR(AVG(SALARY)) AS 평균
	 , MAX(SALARY) AS 최대
	 , MIN(SALARY) AS 최소
	 , JOB_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID ,JOB_ID ;
SELECT * FROM JOB_DEPT_SALARY_STATUS;
DROP TABLE JOB_DEPT_SALARY_STATUS;


UPDATE JOB_DEPT_SALARY_STATUS SET(평균, 최대, 최소)=(
SELECT FLOOR(AVG(SALARY*(1+NVL(COMMISSION_PCT,0)))) 
	 , MAX(SALARY*(1+NVL(COMMISSION_PCT,0))) 
	 , MIN(SALARY*(1+NVL(COMMISSION_PCT,0)))
  FROM EMPLOYEES) ;


(SELECT COMMISSION_PCT FROM EMPLOYEES
GROUP BY DEPARTMENT_ID ,JOB_ID)

