/*
 * 가장 많은 사원수를 가지는 부서 TOP3를 구하세요
 */
SELECT 순위
	 , DEPARTMENT_ID
	 , 사원수
  FROM (SELECT DEPARTMENT_ID	
  			 , COUNT(*) AS 사원수
		     , RANK() OVER(ORDER BY COUNT(*) DESC) AS 순위
		FROM EMPLOYEES
	   GROUP BY DEPARTMENT_ID)
 WHERE 순위<=3;
	
	SELECT DEPARTMENT_ID		
		 , COUNT(*) 
	  FROM EMPLOYEES
	 GROUP BY DEPARTMENT_ID;
	
/*
 * 평균급여가 가장 높은 부서 TOP3를 구하세요. ( 부서 ID 와 부서명이 같이 조회될 수 있게 하세요.)
 */
WITH EMP_SALARY
AS(SELECT E.DEPARTMENT_ID	
  			 , ROUND(AVG(SALARY),2) AS 평균급여
		     , RANK() OVER(ORDER BY AVG(SALARY) DESC) AS 순위
		     , D.DEPARTMENT_NAME 
		FROM EMPLOYEES E
		JOIN DEPARTMENTS D
		  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
	   GROUP BY E.DEPARTMENT_ID, D.DEPARTMENT_NAME)
SELECT 순위
	 , DEPARTMENT_ID
	 , DEPARTMENT_NAME
	 , 평균급여
  FROM EMP_SALARY
WHERE 순위<=3;
	  
	SELECT E.DEPARTMENT_ID	
  			 , ROUND(AVG(SALARY),2) AS 평균급여
		     , D.DEPARTMENT_NAME 
		FROM EMPLOYEES E
		JOIN DEPARTMENTS D
		  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
	   GROUP BY E.DEPARTMENT_ID, D.DEPARTMENT_NAME ;
	
/*
 * 가장 최근에 입사한 사원 5명이 소속되어 있는 부서를 찾으세요.
 */
	  
SELECT ROWNUM
	 , DEPARTMENT_ID 
	 , DEPARTMENT_NAME 
	 , HIRE_DATE
  FROM(
	SELECT E.HIRE_DATE 
		 , E.DEPARTMENT_ID 
		 , D.DEPARTMENT_NAME 
	FROM EMPLOYEES E
	JOIN DEPARTMENTS D
	  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
	  ORDER BY HIRE_DATE DESC )
 WHERE ROWNUM<=5;

/*
 * 1990 ~1999년도에 입사한 사원들 중 가장 많은 급여를 받는 사원 5명을 찾으세요.
 */
SELECT ROWNUM
	 , FIRST_NAME 
	 , LAST_NAME 
	 , SALARY 
	 , HIRE_DATE
  FROM(
	SELECT FIRST_NAME 
		 , LAST_NAME 
		 , SALARY 
		 , HIRE_DATE
		 FROM EMPLOYEES
	WHERE HIRE_DATE BETWEEN TO_DATE(19900101) AND TO_DATE(19991231)
	ORDER BY SALARY DESC)
WHERE ROWNUM<=5;



	  
	  

