/*
 * DEPARTMENTS 테이블과 LOCATIONS 테이블을 사용하여 각 부서가 어느 지역에
 * 위치하는지 알아보세요.
 */
SELECT * FROM DEPARTMENTS;
SELECT * FROM LOCATIONS ;
SELECT * FROM EMPLOYEES;

SELECT D.DEPARTMENT_NAME 
     , L.STATE_PROVINCE 
     , L.CITY
     , L.COUNTRY_ID 
FROM DEPARTMENTS D
JOIN LOCATIONS L 
  ON D.LOCATION_ID =L.LOCATION_ID ;

/*
 * 지역별로 몇개의 부서가 배치되었는지 알아보세요.
 */
SELECT L.STATE_PROVINCE  
	 , COUNT(*)
  FROM DEPARTMENTS D
  JOIN LOCATIONS L 
    ON D.LOCATION_ID =L.LOCATION_ID 
    GROUP BY  L.STATE_PROVINCE ;
 
/*
 * 지역별 사원수가 얼마나 되는지 알아보세요
 */
SELECT COUNT(*)
     , L.STATE_PROVINCE
  FROM EMPLOYEES E
  JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID =D.DEPARTMENT_ID 
  JOIN LOCATIONS L 
    ON D.LOCATION_ID = L.LOCATION_ID
  GROUP BY L.STATE_PROVINCE  ;

   
