
SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;
SELECT * FROM JOBS;
ALTER TABLE DEPARTMENTS ADD EMP_TOTAL NUMBER DEFAULT 0;



UPDATE DEPARTMENTS D1
   SET EMP_TOTAL = (SELECT CNT
                      FROM (SELECT DEPARTMENT_ID AS DEPT_ID
                                 , COUNT(*) AS CNT
                              FROM EMPLOYEES E1
                             GROUP BY DEPARTMENT_ID)
                     WHERE DEPT_ID = D1.DEPARTMENT_ID);     		   
								     		   

CREATE OR REPLACE PROCEDURE PROC_ADD_EMPLOYEE(
       FNAME VARCHAR2
     , LNAME VARCHAR2
     , EM VARCHAR2
     , JOBID VARCHAR2
     , DEPTID NUMBER)
IS 
	EMPID NUMBER;
	SAL NUMBER;
	EJOB VARCHAR2(40);
	EDEPT NUMBER;
BEGIN 
	SELECT MAX(EMPLOYEE_ID)+1 INTO EMPID FROM EMPLOYEES;
    SELECT JOB_ID, MIN_SALARY INTO EJOB, SAL FROM JOBS WHERE JOB_ID =JOBID;
    SELECT DEPARTMENT_ID  INTO EDEPT FROM DEPARTMENTS WHERE DEPARTMENT_ID  =DEPTID;
   
	INSERT INTO EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME,EMAIL,HIRE_DATE,SALARY, JOB_ID, DEPARTMENT_ID) VALUES(EMPID,FNAME,LNAME,EM,SYSDATE,SAL,JOBID,DEPTID);
	
	/*UPDATE DEPARTMENTS D
	   SET EMP_TOTAL = EMP_TOTAL +1
	 WHERE D.DEPARTMENT_ID= DEPTID; */
	--TRIGGER로  대체함			 
	COMMIT;
EXCEPTION 
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('직무코드 또는 부서ID가 존재하지 않습니다.');
	ROLLBACK;
END;



BEGIN
	PROC_ADD_EMPLOYEE('FNAME','LNAME','FL','IT_PROG',60);
END;

BEGIN
	PROC_DEL_EMPLOYEE(213);
END;
	

DROP TRIGGER UPDATE_EMP_TOTAL;

CREATE OR REPLACE TRIGGER UPDATE_EMP_TOTAL
	AFTER INSERT 
	ON EMPLOYEES
	FOR EACH ROW 
BEGIN 
	UPDATE DEPARTMENTS D
       SET EMP_TOTAL = EMP_TOTAL +1
     WHERE DEPARTMENT_ID= :NEW.DEPARTMENT_ID;
END;


CREATE OR REPLACE PROCEDURE PROC_MOD_EMPLOYEE(
       EMP_ID NUMBER
     , SAL NUMBER
     , JOBID VARCHAR2
     , DEPTID VARCHAR2)
IS 
VAR_DEPTID NUMBER;
BEGIN 
	SELECT DEPARTMENT_ID INTO VAR_DEPTID FROM EMPLOYEES WHERE EMPLOYEE_ID = EMP_ID;

	IF VAR_DEPTID <> DEPTID THEN
		UPDATE DEPARTMENTS 
		   SET EMP_TOTAL = EMP_TOTAL-1
		 WHERE DEPARTMENT_ID = VAR_DEPTID;

		UPDATE DEPARTMENTS 
		   SET EMP_TOTAL = EMP_TOTAL+1
		 WHERE DEPARTMENT_ID = DEPTID;
	END IF;
	UPDATE EMPLOYEES 
	   SET SALARY =SAL 
	     , JOB_ID =JOBID 
	     , DEPARTMENT_ID = DEPTID
	 WHERE EMPLOYEE_ID =EMP_ID;
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('해당 사원이 존재하지 않습니다');
		ROLLBACK;
END;


CREATE OR REPLACE PROCEDURE PROC_DEL_EMPLOYEE(
       EMP_ID NUMBER)
IS 
	   VAR_DEPTID NUMBER;
BEGIN 
	SELECT DEPARTMENT_ID INTO VAR_DEPTID FROM EMPLOYEES WHERE EMPLOYEE_ID= EMP_ID;
	DELETE FROM EMPLOYEES WHERE EMPLOYEE_ID= EMP_ID;
--	UPDATE DEPARTMENTS 
--	   SET EMP_TOTAL = EMP_TOTAL-1
--	 WHERE DEPARTMENT_ID = VAR_DEPTID;
	--TRIGGER로 대체
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('해당 사원이 존재하지 않습니다');
		ROLLBACK;
END;


CREATE OR REPLACE TRIGGER DEL_EMP_TOTAL
	AFTER DELETE 
	ON EMPLOYEES
	FOR EACH ROW
BEGIN 
	UPDATE DEPARTMENTS D 
	   SET EMP_TOTAL = EMP_TOTAL -1
	 WHERE DEPARTMENT_ID =:OLD.DEPARTMENT_ID;
END;







BEGIN
	PROC_DEL_EMPLOYEE(213);
END;




SELECT * FROM USER_ERRORS;